### PR TITLE
Ken's integration test for SolrSearch with test Solr server

### PR DESCRIPTION
**Pull request by kenprice**
Set of integration tests that verifies that `SolrSearch`'s query plays well with an actual Solr server.
- Test for:
  - `query` should return exactly one result for some keyword unique to exactly one document.
  - `query` should return no results for empty list of search terms.
  - `query` should return multiple results for keywords common to more than one document.
- New entry for `config.conf`, `TestSolrApiUrl`. Put the URL to your Solr test server here. `README.md` updated with missing info about config.
- Modify `travis.yml` so `config.conf` gets written to with the URL to our Solr test server. Jillian's server URL is hard-coded in the YAML file. Sorry :( Maybe we can pull this URL from environment variables? Can we set custom env vars in Travis outside the YAML file?

### CODE REVIEW

**Comment by idmontie** [comment]
Just a quick question, are there steps to set up a solr server documented anywhere?

**Comment by kenprice** [comment]
@idmontie Yes, [in this wiki entry](https://github.com/gios-asu/search-api/wiki/Setting-up-a-SOLR-test-server) I detail how the Solr test server should be set up. However! The actual test data to be committed to the Solr core isn't in the wiki. I have a script locally to repeatedly curl Jillian's test server to populate it with some docs. I will need to think of a way to easily reproduce the state of the test server.

**Comment by idmontie** [comment]
Great thanks @kenprice. One thing you can do is just add that sort script to a new folder at the root of the project. Maybe something like `/setup/solr-setup.sh` or something.

**Comment by kenprice** [comment]
@idmontie If everything else is ok, can you merge & close? This way there's at least one integration test in `develop`. I can have the setup and test data stuff in my next PR.

**Comment by rraub** [comment]
We can set [custom variables in travis-ci](https://docs.travis-ci.com/user/environment-variables/) however I think you need admin rights for the repo to do it. I personally think its fine for the default/example config to work in travis. Yeah we can merge this one in and wait to add the `solr-setup.sh` stuff in another PR.

**Pull request merged**
